### ISSUE TITLE
STRique 

### ISSUE THREAD

**Issue by tcarlile** [giesselmann/STRique#18]
Thanks for the great package. I successfully used it ~6 months ago on a data set that I generated, and it worked beautifully. 

I'm back in lab now generating some new data that I am trying to analyze. The index command works, but the count command does not. I'm getting an error running it on the new datasets, the old data sets, and with the STRique_test.py. I'm getting the same errors with both installed versions. The outputs are below. This is probably some issue on our end, but was hoping you might have an insight into what the issue is.
Thanks,
Thomas

The failed command trying to run an old analysis that was previously successful:
`python3 /camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py count --out test.txt --algn TST11465.sam --t 8 reads.fofn /camhpc/pkg/STRique/0.3.0/centos7/models/r9_4_450bps.model TST11465_C9.tsv
24.06.2020 16:45:52 [PID 6980] [WARNING] Factory: Unexpected error in Worker, proceeding wiht remaining reads.
Traceback (most recent call last):

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 758, in __worker__
    input = worker_callable(**input)

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 684, in detect
    self.__init_hmm__()

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 645, in __init_hmm__
    self.repeatCounter.add_target(target_name, repeat, prefix, suffix)

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 567, in add_target
    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 403, in __init__
    self.__build_model__()

  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique.py", line 432, in __build_model__
    self.bake(merge='All')

  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake

  File "/camhpc/pkg/anaconda3/2019.03/centos7/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]

KeyError: 0`

The results from STRique_test.py (the same for both versions)

`python /camhpc/pkg/STRique/0.3.0/centos7/bin/STRique_test.py 
EEEE
======================================================================
ERROR: test_Detection (__main__.DetectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique_test.py", line 55, in test_Detection
    dt.add_target('c9orf72', repeat, prefix, suffix)
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 567, in add_target
    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 403, in __init__
    self.__build_model__()
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 432, in __build_model__
    self.bake(merge='All')
  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/camhpc/pkg/anaconda3/2019.03/centos7/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

======================================================================
ERROR: test_Interpolation (__main__.DetectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique_test.py", line 75, in test_Interpolation
    dt.add_target('fmr1', repeat, prefix, suffix)
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 567, in add_target
    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 403, in __init__
    self.__build_model__()
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 432, in __build_model__
    self.bake(merge='All')
  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/camhpc/pkg/anaconda3/2019.03/centos7/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

======================================================================
ERROR: test_Modification (__main__.DetectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique_test.py", line 114, in test_Modification
    dt.add_target('c9orf72', repeat, prefix, suffix)
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 567, in add_target
    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 403, in __init__
    self.__build_model__()
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 432, in __build_model__
    self.bake(merge='All')
  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/camhpc/pkg/anaconda3/2019.03/centos7/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

======================================================================
ERROR: test_Normalization (__main__.DetectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/camhpc/pkg/STRique/0.3.0/centos7/bin/STRique_test.py", line 93, in test_Normalization
    dt.add_target('c9orf72', repeat, prefix, suffix)
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 567, in add_target
    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 403, in __init__
    self.__build_model__()
  File "/camhpc/pkg/STRique/0.3.0/centos7/scripts/STRique.py", line 432, in __build_model__
    self.bake(merge='All')
  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/camhpc/pkg/anaconda3/2019.03/centos7/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

----------------------------------------------------------------------
Ran 4 tests in 0.399s

FAILED (errors=4)`

**Comment by giesselmann** [comment]
Hi Thomas,
The package didn't change in the past 6 months, I guess it must be an installation issue. 
As long as the tests don't pass, there's no chance for the data.
For me it looks like the pomegranate and networkx python packages don't work together. This has been an issue in the past, but there's no good HMM alternatives as far as I know.
Please run the following in the python (virtual environment) of STRique:
> pip freeze

Look for the versions of pomegranate and networkx, they should be the same as in the requirements.txt file.
If they got updated by another package in the same python installation try isolating STRique into its private virtual environment.
If that doesn't work please post the complete output of pip freeze here.

Pay

**Comment by tcarlile** [comment]
Hi Pay,
There must have been some change in the anaconda environment that STRique was installed in. I got our cluster people to reinstall, and that fixed the problem. Again, thanks for a great package.
Best,
Thomas
