### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by woodoo46** [giesselmann/STRique#31]
Hi, there,

We recently upgraded to STRique 0.4.2; but when we tried to run the program, we had the following weird error:

03.01.2022 14:00:58 [PID 46032] [WARNING] Factory: Unexpected error in Worker, proceeding wiht remaining reads.

Traceback (most recent call last):

File "/tools/STRique/0.4.2/scripts/STRique.py", line 758, in __worker__

    input = worker_callable(**input)

 

  File "/tools/STRique/0.4.2/scripts/STRique.py", line 684, in detect

    self.__init_hmm__()

 

  File "/tools/STRique/0.4.2/scripts/STRique.py", line 645, in __init_hmm__

    self.repeatCounter.add_target(target_name, repeat, prefix, suffix)

 

  File "/tools/STRique/0.4.2/scripts/STRique.py", line 567, in add_target

    flankedRepeatHMM(repeat, prefix, suffix, self.pm, self.HMM_config),

 

  File "/tools/STRique/0.4.2/scripts/STRique.py", line 403, in __init__

    self.__build_model__()

 

  File "/tools/STRique/0.4.2/scripts/STRique.py", line 432, in __build_model__

    self.bake(merge='All')

 

  File "pomegranate/hmm.pyx", line 869, in pomegranate.hmm.HiddenMarkovModel.bake

 

  File "/tools/STRique/0.4.2/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 729, in <genexpr>

    for nbr, dd in nbrs.items()

 

RuntimeError: dictionary keys changed during iteration

**Comment by giesselmann** [comment]
Hi there,
that is very likely a version mismatch of pomegranate, can you check that all installed packages match the versions in the requirements.txt? E.g. pomegranate == 0.10.0
